version: '3.6'

services:
  web:
    build: .
    image: ruby-jekyll
    volumes:
      - ./:/app
    working_dir: /app
    command: bundle exec jekyll serve --host 0.0.0.0
    ports:
      - 4000:4000
